[tool.poetry]
name = "hello-python"
version = "0.1.0"
description = ""
authors = ["RyushiAok <55625375+RyushiAok@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "hello_python"}]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.24.3"
notebook = "^6.5.4"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
